hajimari:
  name: Mr.L
  title: 主页
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.lhy.me"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.lhy.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
    globalBookmarks:
      - group: Homelab
        bookmarks:
          - name: Documentation
            url: https://homelab.lhy.me
          - name: Gitea repository
            url: https://git.lhy.me/ops/homelab
      - group: Managed services
        bookmarks:
          - name: Terraform Cloud
            url: https://app.terraform.io
          - name: Cloudflare
            url: https://dash.cloudflare.com
      - group: Persional words
        bookmarks:
          - name: Github
            url: https://github.com/lianghuiyuan          
          - name: Long time no see!
            url: https://github.lhy.me              
  persistence:
    data:
      enabled: false
