grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.lhy.me"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hajimari.io/appName: Grafana
      hajimari.io/icon: chart-bar
    hosts:
      - &host grafana.lhy.me
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.lhy.me
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.lhy.me/auth
      token_url: https://dex.lhy.me/token
      api_url: https://dex.lhy.me/userinfo
